"""
ascii_art.py
------------
Every picture in this app is drawn with nothing but text.

The centrepiece (the Uzumaki swirl) is not hard-coded: it is generated by
walking an Archimedean spiral and stamping Naruto keywords along the path,
so the shape is literally made out of words like NARUTO, KONOHA and RAMEN.
"""

import math

# The words the big swirl is woven from.
KEYWORD_STRING = (
    "NARUTO UZUMAKI KONOHA RASENGAN HOKAGE ICHIRAKU RAMEN SHINOBI KURAMA "
    "SASUKE SAKURA KAKASHI JIRAIYA HINATA SHIKAMARU CHAKRA SHARINGAN "
    "BYAKUGAN DATTEBAYO NINDO SANNIN GENIN CHUNIN JONIN KAGEBUNSHIN "
    "SENNIN MODO AKATSUKI SUNA TAIJUTSU NINJUTSU GENJUTSU KUNAI SHURIKEN "
    "HITAIATE WILLOFFIRE NEVERGIVEUP BELIEVEIT "
)

KEYWORDS = [w for w in KEYWORD_STRING.split() if w]

# Characters are about twice as tall as they are wide, so horizontal
# distances get multiplied by this to keep circles looking like circles.
CHAR_ASPECT = 0.5


def _blank(width, height):
    return [[" "] * width for _ in range(height)]


def _stamp(grid, col, row, ch):
    if 0 <= row < len(grid) and 0 <= col < len(grid[0]):
        grid[row][col] = ch


def uzumaki_swirl(width=96, height=44, turns=2.25, tail=True):
    """Draw the Uzumaki / Konoha swirl out of keyword letters.

    Returns a single string ready to drop inside a <pre> block.
    """
    grid = _blank(width, height)
    # The swirl sits up and to the right so the leaf tail has room to sweep
    # away towards the bottom-left corner.
    cx, cy = width * 0.58, height * 0.44

    # Largest radius that still fits the canvas in every direction.
    max_r = min(cx * CHAR_ASPECT, (width - cx) * CHAR_ASPECT, cy, height - cy) - 1.0
    t_end = 2 * math.pi * turns
    a = max_r / t_end

    letters = [c for c in KEYWORD_STRING.replace(" ", "\u00b7")]
    state = {"i": 0, "last": None}

    def plot(x, y):
        """x, y are in aspect-corrected space; convert back to cells."""
        col = int(round(cx + x / CHAR_ASPECT))
        row = int(round(cy + y))
        if state["last"] == (col, row):
            return
        state["last"] = (col, row)
        i = state["i"]
        # Two cells wide so the stroke reads evenly at this aspect ratio.
        _stamp(grid, col, row, letters[i % len(letters)])
        _stamp(grid, col + 1, row, letters[(i + 1) % len(letters)])
        state["i"] = i + 2

    # --- the spiral itself -------------------------------------------------
    # Step along the curve by arc length so the stroke never breaks up,
    # however far from the centre it gets.
    step = 0.35
    t = 0.0
    while t <= t_end:
        r = a * t
        plot(r * math.cos(t), r * math.sin(t))
        speed = a * math.sqrt(1 + t * t)
        t += step / max(speed, 1e-6)

    # --- the leaf tail hooking off the outer end ---------------------------
    if tail:
        ex, ey = max_r * math.cos(t_end), max_r * math.sin(t_end)
        # Quadratic curve sweeping down-left, the way the Konoha mark does.
        p0 = (ex, ey)
        p1 = (ex - max_r * 0.55, ey + max_r * 0.25)
        p2 = (ex - max_r * 1.45, ey - max_r * 0.15)
        for i in range(4000 + 1):
            t = i / 4000
            u = 1 - t
            x = u * u * p0[0] + 2 * u * t * p1[0] + t * t * p2[0]
            y = u * u * p0[1] + 2 * u * t * p1[1] + t * t * p2[1]
            plot(x, y)

    lines = ["".join(row).rstrip() for row in grid]
    while lines and not lines[0]:
        lines.pop(0)
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines)


LOGO = r"""
 ███    ██  █████  ██████  ██    ██ ████████  ██████
 ████   ██ ██   ██ ██   ██ ██    ██    ██    ██    ██
 ██ ██  ██ ███████ ██████  ██    ██    ██    ██    ██
 ██  ██ ██ ██   ██ ██   ██ ██    ██    ██    ██    ██
 ██   ████ ██   ██ ██   ██  ██████     ██     ██████
"""

SHREYA = r"""
 ███████ ██   ██ ██████  ███████ ██    ██  █████
 ██      ██   ██ ██   ██ ██       ██  ██  ██   ██
 ███████ ███████ ██████  █████     ████   ███████
      ██ ██   ██ ██   ██ ██         ██    ██   ██
 ███████ ██   ██ ██   ██ ███████    ██    ██   ██
"""

FACE = r"""
         \\\\\     |||||     /////     \\\\\     |||||
          \\\\\    |||||    /////     \\\\\     |||||
    ________________________________________________________
   |                                                        |
   |  ####  ####  ####  ####   (卍)   ####  ####  ####  ###  |
   |________________________________________________________|
        |                                              |
        |      ______                    ______        |
        |     /  ..  \                  /  ..  \       |
        |    |  (●)   |                |   (●)  |      |
        |     \______/                  \______/       |
   _____|                                              |_____
  /     |   ~~~~~~~~                      ~~~~~~~~     |     \
 |   O  |   ~~~~~~~~         ______       ~~~~~~~~     |  O   |
  \_____|   ~~~~~~~~        /      \      ~~~~~~~~     |_____/
        |                   \  __  /                   |
        |                    \____/                    |
         \              \              /              /
          \              \____________/              /
           \____________________________________ ___/
"""

RAMEN = r"""
        ~  ~   ~    ~   ~
          ~   ~   ~    ~
     ________________________
     \   #### ~~~~ #### ~~  /
      \  ~~~~ #### ~~~~ ####/
       \  ####  ~~~~  ####  /
        \______________WE__/
           \____________/
"""

HEADBAND = r"""
  ═══════════════════════════════════════════════════
  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  卍  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
  ═══════════════════════════════════════════════════
"""


def rasengan(frame=0):
    """A tiny spinning orb of chakra. Pass an increasing frame number."""
    rings = ["◜◝", "◝◞", "◞◟", "◟◜"]
    spin = rings[frame % len(rings)]
    return f"""
        .  *  .   . *   .
     *   ({spin[0]}{spin[1]})   *
   .  *  ( ◍ CHAKRA ◍ )  *  .
     *   ({spin[1]}{spin[0]})   *
        .  *  .   . *   .
"""


def keyword_banner(words, width=64):
    """Wrap a list of words into a neat centred block of text."""
    lines, line = [], ""
    for w in words:
        candidate = (line + " · " + w) if line else w
        if len(candidate) > width:
            lines.append(line.center(width))
            line = w
        else:
            line = candidate
    if line:
        lines.append(line.center(width))
    return "\n".join(lines)


if __name__ == "__main__":
    print(LOGO)
    print(uzumaki_swirl())
    print(FACE)
